[2021-04-06 03:10:41,537] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Load_songplays_fact_table 2021-03-24T00:00:00+00:00 [queued]>
[2021-04-06 03:10:41,555] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: udac_example_dag.Load_songplays_fact_table 2021-03-24T00:00:00+00:00 [queued]>
[2021-04-06 03:10:41,556] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-04-06 03:10:41,557] {taskinstance.py:1043} INFO - Starting attempt 1 of 4
[2021-04-06 03:10:41,558] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-04-06 03:10:41,570] {taskinstance.py:1063} INFO - Executing <Task(LoadFactOperator): Load_songplays_fact_table> on 2021-03-24T00:00:00+00:00
[2021-04-06 03:10:41,577] {standard_task_runner.py:52} INFO - Started process 181 to run task
[2021-04-06 03:10:41,581] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'udac_example_dag', 'Load_songplays_fact_table', '2021-03-24T00:00:00+00:00', '--job-id', '72', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/udac_example_dag.py', '--cfg-path', '/tmp/tmpgs6brhso', '--error-file', '/tmp/tmp75sp94yz']
[2021-04-06 03:10:41,583] {standard_task_runner.py:77} INFO - Job 72: Subtask Load_songplays_fact_table
[2021-04-06 03:10:41,632] {logging_mixin.py:104} INFO - Running <TaskInstance: udac_example_dag.Load_songplays_fact_table 2021-03-24T00:00:00+00:00 [running]> on host 0ccaa9d2b3f1
[2021-04-06 03:10:41,677] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=udacity
AIRFLOW_CTX_DAG_ID=udac_example_dag
AIRFLOW_CTX_TASK_ID=Load_songplays_fact_table
AIRFLOW_CTX_EXECUTION_DATE=2021-03-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-24T00:00:00+00:00
[2021-04-06 03:10:41,679] {load_fact.py:25} INFO - Clearing table...
[2021-04-06 03:10:41,688] {base.py:74} INFO - Using connection to: id: redshift. Host: sparkify-redshift.c5c7ovgg2wrr.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: sparkify-song-analytics, Login: data.engineer, Password: XXXXXXXX, extra: None
[2021-04-06 03:10:42,330] {dbapi.py:180} INFO - Running statement: 
        BEGIN; 
        DELETE FROM songplays; 
        COMMIT;
    , parameters: None
[2021-04-06 03:10:42,648] {dbapi.py:186} INFO - Rows affected: -1
[2021-04-06 03:10:42,733] {load_fact.py:28} INFO - Loading data...
[2021-04-06 03:10:42,744] {base.py:74} INFO - Using connection to: id: redshift. Host: sparkify-redshift.c5c7ovgg2wrr.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: sparkify-song-analytics, Login: data.engineer, Password: XXXXXXXX, extra: None
[2021-04-06 03:10:43,321] {dbapi.py:180} INFO - Running statement: 
        BEGIN; 
        INSERT INTO songplays (
            playid,
            start_time,
            userid,
            level,
            songid,
            artistid,
            sessionid,
            location,
            user_agent
        )
        SELECT
                md5(events.sessionid || events.start_time) songplay_id,
                events.start_time, 
                events.userid, 
                events.level, 
                songs.song_id, 
                songs.artist_id, 
                events.sessionid, 
                events.location, 
                events.useragent
                FROM (SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
            FROM staging_events
            WHERE page='NextSong') events
            LEFT JOIN staging_songs songs
            ON events.song = songs.title
                AND events.artist = songs.artist_name
                AND events.length = songs.duration;
        COMMIT;
    , parameters: None
[2021-04-06 03:14:32,306] {taskinstance.py:1455} ERROR - could not open relation with OID 101589
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/opt/airflow/plugins/operators/load_fact.py", line 29, in execute
    redshift.run(self.load_data_sql)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 184, in run
    cur.execute(sql_statement)
psycopg2.errors.InternalError_: could not open relation with OID 101589

[2021-04-06 03:14:32,313] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=udac_example_dag, task_id=Load_songplays_fact_table, execution_date=20210324T000000, start_date=20210406T031041, end_date=20210406T031432
[2021-04-06 03:14:32,372] {local_task_job.py:146} INFO - Task exited with return code 1
